name: panda
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  freezed: ^2.5.7
  injectable: ^2.5.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  web_socket_channel: ^3.0.1
  json_serializable: ^6.9.0
  auto_route: ^9.3.0+1
  auto_route_generator: ^9.0.0
  timeago: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
